[package]
name = "The_Fibonacchi_sequence"
version = "0.2.0"
authors = ["oskar.dudzinski@yahoo.com"]
edition = "2018"
description = "First program in Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
